import Playing from "@/organisms/Playing";
import RecentlyPlayed from "@/organisms/RecentlyPlayed";
import TopTracks from "@/organisms/TopTracks";
import css from "./styles.module.css";
import Head from "next/head";
import TopArtists from "@/organisms/TopArtists";

export default function Music() {
  return (
    <>
      <Head>
        <title>Rajbir Johar | Music</title>
        <meta
          content="Music that I am listening to generated by Spotify"
          name="description"
        />
      </Head>
      <header>
        <h1>Music</h1>
        <p>Music that&#39;s inspired me lately.</p>
      </header>
      <section>
        <Playing />
        <TopArtists />
        <div className={css.trackswrapper}>
          <TopTracks />
          <RecentlyPlayed />
        </div>
      </section>
    </>
  );
}
