import Playing from "core/organisms/Playing";
import RecentlyPlayed from "core/organisms/RecentlyPlayed";
import TopTracks from "core/organisms/TopTracks";
import css from "./styles.module.css";
import Head from "next/head";
import TopArtists from "core/organisms/TopArtists";
import Page from "@/templates/Page";

export default function Music() {
  return (
    <>
      <Head>
        <title>Rajbir Johar | Music</title>
        <meta
          content="Music that I am listening to generated by Spotify"
          name="description"
        />
      </Head>
      <Page>
        <article className={css.wrapper}>
          <header>
            <h1>Music</h1>
            <p>Music that&#39;s inspired me lately.</p>
          </header>
          <Playing />
          <TopArtists />
          <div className={css.trackswrapper}>
            <TopTracks />
            <RecentlyPlayed />
          </div>
        </article>
      </Page>
    </>
  );
}
